schema_version = "1.0.0"

id = "fspy_blender_ng"
version = "2.0.0"
name = "fSpy Importer"
tagline = "Import image and camera settings from fSpy project"
maintainer = "Per Gantelius, yyc12345 <yyc12321@outlook.com>"
type = "add-on"

website = "https://github.com/yyc12345/fspy_blender_ng"

tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Import fSpy project file from disk"
